version: "3.8"

services:
  web:
    build:
      context: .
      target: base
    container_name: code_comparison_web
    command: mix phx.server
    restart: unless-stopped
    env_file:
      - .env-sample
    environment:
      - MIX_ENV=test
    ports:
      - 4000:4000
    volumes:
      - .:/code_comparison
